// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/svc/bill/bill.proto

package billpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayType int32

const (
	PayType_BillTypeInvalid  PayType = 0
	PayType_BillTypeHalved   PayType = 1
	PayType_BillTypeAdvanced PayType = 2
)

// Enum value maps for PayType.
var (
	PayType_name = map[int32]string{
		0: "BillTypeInvalid",
		1: "BillTypeHalved",
		2: "BillTypeAdvanced",
	}
	PayType_value = map[string]int32{
		"BillTypeInvalid":  0,
		"BillTypeHalved":   1,
		"BillTypeAdvanced": 2,
	}
)

func (x PayType) Enum() *PayType {
	p := new(PayType)
	*p = x
	return p
}

func (x PayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_svc_bill_bill_proto_enumTypes[0].Descriptor()
}

func (PayType) Type() protoreflect.EnumType {
	return &file_proto_svc_bill_bill_proto_enumTypes[0]
}

func (x PayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayType.Descriptor instead.
func (PayType) EnumDescriptor() ([]byte, []int) {
	return file_proto_svc_bill_bill_proto_rawDescGZIP(), []int{0}
}

type Bill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId  string  `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	PayerId string  `protobuf:"bytes,2,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId string  `protobuf:"bytes,3,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	Amount  float32 `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PayType PayType `protobuf:"varint,5,opt,name=pay_type,json=payType,proto3,enum=svc.bill.PayType" json:"pay_type,omitempty"`
}

func (x *Bill) Reset() {
	*x = Bill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_bill_bill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_bill_bill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_proto_svc_bill_bill_proto_rawDescGZIP(), []int{0}
}

func (x *Bill) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

func (x *Bill) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *Bill) GetPayeeId() string {
	if x != nil {
		return x.PayeeId
	}
	return ""
}

func (x *Bill) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bill) GetPayType() PayType {
	if x != nil {
		return x.PayType
	}
	return PayType_BillTypeInvalid
}

var File_proto_svc_bill_bill_proto protoreflect.FileDescriptor

var file_proto_svc_bill_bill_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c,
	0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x76, 0x63,
	0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x9b, 0x01, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x17,
	0x0a, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69,
	0x6c, 0x6c, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x2a, 0x48, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13,
	0x0a, 0x0f, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x48,
	0x61, 0x6c, 0x76, 0x65, 0x64, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x69, 0x6c, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x10, 0x02, 0x42, 0x1e, 0x5a,
	0x1c, 0x70, 0x61, 0x72, 0x72, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76,
	0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x3b, 0x62, 0x69, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_svc_bill_bill_proto_rawDescOnce sync.Once
	file_proto_svc_bill_bill_proto_rawDescData = file_proto_svc_bill_bill_proto_rawDesc
)

func file_proto_svc_bill_bill_proto_rawDescGZIP() []byte {
	file_proto_svc_bill_bill_proto_rawDescOnce.Do(func() {
		file_proto_svc_bill_bill_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_svc_bill_bill_proto_rawDescData)
	})
	return file_proto_svc_bill_bill_proto_rawDescData
}

var file_proto_svc_bill_bill_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_svc_bill_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_svc_bill_bill_proto_goTypes = []interface{}{
	(PayType)(0), // 0: svc.bill.PayType
	(*Bill)(nil), // 1: svc.bill.Bill
}
var file_proto_svc_bill_bill_proto_depIdxs = []int32{
	0, // 0: svc.bill.Bill.pay_type:type_name -> svc.bill.PayType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_svc_bill_bill_proto_init() }
func file_proto_svc_bill_bill_proto_init() {
	if File_proto_svc_bill_bill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_svc_bill_bill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_svc_bill_bill_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_svc_bill_bill_proto_goTypes,
		DependencyIndexes: file_proto_svc_bill_bill_proto_depIdxs,
		EnumInfos:         file_proto_svc_bill_bill_proto_enumTypes,
		MessageInfos:      file_proto_svc_bill_bill_proto_msgTypes,
	}.Build()
	File_proto_svc_bill_bill_proto = out.File
	file_proto_svc_bill_bill_proto_rawDesc = nil
	file_proto_svc_bill_bill_proto_goTypes = nil
	file_proto_svc_bill_bill_proto_depIdxs = nil
}
