version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev:aa0ab4cc0cea2a06152eb2d8e0c4723b3f02c72c
    ports:
      - "5000:5000"
    container_name: parrot_proxy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml