/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.svc.bill.Bill', null, global);
goog.exportSymbol('proto.svc.bill.PayType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.svc.bill.Bill = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.svc.bill.Bill, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.svc.bill.Bill.displayName = 'proto.svc.bill.Bill';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.svc.bill.Bill.prototype.toObject = function(opt_includeInstance) {
  return proto.svc.bill.Bill.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.svc.bill.Bill} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.svc.bill.Bill.toObject = function(includeInstance, msg) {
  var f, obj = {
    billId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    payerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    payeeId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    amount: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    payType: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.svc.bill.Bill}
 */
proto.svc.bill.Bill.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.svc.bill.Bill;
  return proto.svc.bill.Bill.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.svc.bill.Bill} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.svc.bill.Bill}
 */
proto.svc.bill.Bill.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBillId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayerId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayeeId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAmount(value);
      break;
    case 5:
      var value = /** @type {!proto.svc.bill.PayType} */ (reader.readEnum());
      msg.setPayType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.svc.bill.Bill.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.svc.bill.Bill.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.svc.bill.Bill} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.svc.bill.Bill.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBillId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPayerId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPayeeId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getPayType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional string bill_id = 1;
 * @return {string}
 */
proto.svc.bill.Bill.prototype.getBillId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.svc.bill.Bill.prototype.setBillId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string payer_id = 2;
 * @return {string}
 */
proto.svc.bill.Bill.prototype.getPayerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.svc.bill.Bill.prototype.setPayerId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string payee_id = 3;
 * @return {string}
 */
proto.svc.bill.Bill.prototype.getPayeeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.svc.bill.Bill.prototype.setPayeeId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float amount = 4;
 * @return {number}
 */
proto.svc.bill.Bill.prototype.getAmount = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.svc.bill.Bill.prototype.setAmount = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional PayType pay_type = 5;
 * @return {!proto.svc.bill.PayType}
 */
proto.svc.bill.Bill.prototype.getPayType = function() {
  return /** @type {!proto.svc.bill.PayType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {!proto.svc.bill.PayType} value */
proto.svc.bill.Bill.prototype.setPayType = function(value) {
  jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.svc.bill.PayType = {
  BILLTYPEINVALID: 0,
  BILLTYPEHALVED: 1,
  BILLTYPEADVANCED: 2
};

goog.object.extend(exports, proto.svc.bill);
