// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/bill_api.proto

package billpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_BillTypeInvalid Type = 0
	Type_BillTypeHalf    Type = 1
	Type_BillTypeAdvance Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "BillTypeInvalid",
		1: "BillTypeHalf",
		2: "BillTypeAdvance",
	}
	Type_value = map[string]int32{
		"BillTypeInvalid": 0,
		"BillTypeHalf":    1,
		"BillTypeAdvance": 2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bill_api_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_proto_bill_api_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_bill_api_proto_rawDescGZIP(), []int{0}
}

type AddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        Type     `protobuf:"varint,1,opt,name=type,proto3,enum=bill.Type" json:"type,omitempty"`
	HalfForList []string `protobuf:"bytes,2,rep,name=half_for_list,json=halfForList,proto3" json:"half_for_list,omitempty"`
	Amount      int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bill_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bill_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_bill_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_BillTypeInvalid
}

func (x *AddRequest) GetHalfForList() []string {
	if x != nil {
		return x.HalfForList
	}
	return nil
}

func (x *AddRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrDesc    string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc,proto3" json:"err_desc,omitempty"`
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bill_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bill_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_bill_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AddResponse) GetErrDesc() string {
	if x != nil {
		return x.ErrDesc
	}
	return ""
}

var File_proto_bill_api_proto protoreflect.FileDescriptor

var file_proto_bill_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x68, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x68, 0x61,
	0x6c, 0x66, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x68, 0x61, 0x6c, 0x66, 0x46, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x44, 0x65, 0x73,
	0x63, 0x2a, 0x42, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x69, 0x6c,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x48, 0x61, 0x6c, 0x66, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x42, 0x69, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x76, 0x61,
	0x6e, 0x63, 0x65, 0x10, 0x02, 0x32, 0x34, 0x0a, 0x04, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x2c, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x10, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f,
	0x62, 0x69, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bill_api_proto_rawDescOnce sync.Once
	file_proto_bill_api_proto_rawDescData = file_proto_bill_api_proto_rawDesc
)

func file_proto_bill_api_proto_rawDescGZIP() []byte {
	file_proto_bill_api_proto_rawDescOnce.Do(func() {
		file_proto_bill_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bill_api_proto_rawDescData)
	})
	return file_proto_bill_api_proto_rawDescData
}

var file_proto_bill_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bill_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bill_api_proto_goTypes = []interface{}{
	(Type)(0),           // 0: bill.Type
	(*AddRequest)(nil),  // 1: bill.AddRequest
	(*AddResponse)(nil), // 2: bill.AddResponse
}
var file_proto_bill_api_proto_depIdxs = []int32{
	0, // 0: bill.AddRequest.type:type_name -> bill.Type
	1, // 1: bill.Bill.Add:input_type -> bill.AddRequest
	2, // 2: bill.Bill.Add:output_type -> bill.AddResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bill_api_proto_init() }
func file_proto_bill_api_proto_init() {
	if File_proto_bill_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bill_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bill_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bill_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bill_api_proto_goTypes,
		DependencyIndexes: file_proto_bill_api_proto_depIdxs,
		EnumInfos:         file_proto_bill_api_proto_enumTypes,
		MessageInfos:      file_proto_bill_api_proto_msgTypes,
	}.Build()
	File_proto_bill_api_proto = out.File
	file_proto_bill_api_proto_rawDesc = nil
	file_proto_bill_api_proto_goTypes = nil
	file_proto_bill_api_proto_depIdxs = nil
}
