// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/svc/bill_api.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	bill "parrot/proto/svc/bill"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayType       bill.PayType `protobuf:"varint,1,opt,name=pay_type,json=payType,proto3,enum=svc.bill.PayType" json:"pay_type,omitempty"`
	HalvedForList []string     `protobuf:"bytes,2,rep,name=halved_for_list,json=halvedForList,proto3" json:"halved_for_list,omitempty"`
	Amount        float32      `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AddBillRequest) Reset() {
	*x = AddBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_bill_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBillRequest) ProtoMessage() {}

func (x *AddBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_bill_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBillRequest.ProtoReflect.Descriptor instead.
func (*AddBillRequest) Descriptor() ([]byte, []int) {
	return file_proto_svc_bill_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddBillRequest) GetPayType() bill.PayType {
	if x != nil {
		return x.PayType
	}
	return bill.PayType_BillTypeInvalid
}

func (x *AddBillRequest) GetHalvedForList() []string {
	if x != nil {
		return x.HalvedForList
	}
	return nil
}

func (x *AddBillRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ErrDesc    string `protobuf:"bytes,2,opt,name=err_desc,json=errDesc,proto3" json:"err_desc,omitempty"`
}

func (x *AddBillResponse) Reset() {
	*x = AddBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_bill_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBillResponse) ProtoMessage() {}

func (x *AddBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_bill_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBillResponse.ProtoReflect.Descriptor instead.
func (*AddBillResponse) Descriptor() ([]byte, []int) {
	return file_proto_svc_bill_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddBillResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AddBillResponse) GetErrDesc() string {
	if x != nil {
		return x.ErrDesc
	}
	return ""
}

type GetBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId string `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
}

func (x *GetBillRequest) Reset() {
	*x = GetBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_bill_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillRequest) ProtoMessage() {}

func (x *GetBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_bill_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillRequest.ProtoReflect.Descriptor instead.
func (*GetBillRequest) Descriptor() ([]byte, []int) {
	return file_proto_svc_bill_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillRequest) GetBillId() string {
	if x != nil {
		return x.BillId
	}
	return ""
}

type GetBillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bill *bill.Bill `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
}

func (x *GetBillResponse) Reset() {
	*x = GetBillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_svc_bill_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillResponse) ProtoMessage() {}

func (x *GetBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_svc_bill_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillResponse.ProtoReflect.Descriptor instead.
func (*GetBillResponse) Descriptor() ([]byte, []int) {
	return file_proto_svc_bill_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillResponse) GetBill() *bill.Bill {
	if x != nil {
		return x.Bill
	}
	return nil
}

var File_proto_svc_bill_api_proto protoreflect.FileDescriptor

var file_proto_svc_bill_api_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x76, 0x63, 0x1a,
	0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x2f,
	0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x08,
	0x70, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x6c, 0x6c, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x61,
	0x6c, 0x76, 0x65, 0x64, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x68, 0x61, 0x6c, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4d, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x44, 0x65, 0x73, 0x63, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x69, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69,
	0x6c, 0x6c, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x62, 0x69, 0x6c, 0x6c,
	0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x32, 0x6e, 0x0a, 0x04, 0x42,
	0x69, 0x6c, 0x6c, 0x12, 0x32, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x13, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13,
	0x2e, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x70,
	0x61, 0x72, 0x72, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x76, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_svc_bill_api_proto_rawDescOnce sync.Once
	file_proto_svc_bill_api_proto_rawDescData = file_proto_svc_bill_api_proto_rawDesc
)

func file_proto_svc_bill_api_proto_rawDescGZIP() []byte {
	file_proto_svc_bill_api_proto_rawDescOnce.Do(func() {
		file_proto_svc_bill_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_svc_bill_api_proto_rawDescData)
	})
	return file_proto_svc_bill_api_proto_rawDescData
}

var file_proto_svc_bill_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_svc_bill_api_proto_goTypes = []interface{}{
	(*AddBillRequest)(nil),  // 0: svc.AddBillRequest
	(*AddBillResponse)(nil), // 1: svc.AddBillResponse
	(*GetBillRequest)(nil),  // 2: svc.GetBillRequest
	(*GetBillResponse)(nil), // 3: svc.GetBillResponse
	(bill.PayType)(0),       // 4: svc.bill.PayType
	(*bill.Bill)(nil),       // 5: svc.bill.Bill
}
var file_proto_svc_bill_api_proto_depIdxs = []int32{
	4, // 0: svc.AddBillRequest.pay_type:type_name -> svc.bill.PayType
	5, // 1: svc.GetBillResponse.bill:type_name -> svc.bill.Bill
	0, // 2: svc.Bill.Add:input_type -> svc.AddBillRequest
	2, // 3: svc.Bill.Get:input_type -> svc.GetBillRequest
	1, // 4: svc.Bill.Add:output_type -> svc.AddBillResponse
	3, // 5: svc.Bill.Get:output_type -> svc.GetBillResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_svc_bill_api_proto_init() }
func file_proto_svc_bill_api_proto_init() {
	if File_proto_svc_bill_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_svc_bill_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_svc_bill_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_svc_bill_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_svc_bill_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_svc_bill_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_svc_bill_api_proto_goTypes,
		DependencyIndexes: file_proto_svc_bill_api_proto_depIdxs,
		MessageInfos:      file_proto_svc_bill_api_proto_msgTypes,
	}.Build()
	File_proto_svc_bill_api_proto = out.File
	file_proto_svc_bill_api_proto_rawDesc = nil
	file_proto_svc_bill_api_proto_goTypes = nil
	file_proto_svc_bill_api_proto_depIdxs = nil
}
